db.url=jdbc:mysql://localhost:3306/airline_booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
db.user=root
db.password=root
pool.size=10
pool.acquire.timeout.ms=2000
db.isolation=REPEATABLE_READ
